/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts with derived balances */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Get an account with its derived balance */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /** Delete an account; only allowed when it has no transactions */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update mutable account fields */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{id}/amortization": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Amortization schedule for a loan account */
        get: operations["getAmortization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories (expense and income trees) */
        get: operations["listCategories"];
        put?: never;
        /** Create a category or subcategory */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        /** Get a category */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /** Delete a category; only allowed when it has no subcategories or transactions */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Update mutable category fields */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search transactions */
        get: operations["listTransactions"];
        put?: never;
        /** Record an expense, income, or transfer */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Get a transaction */
        get: operations["getTransaction"];
        /** Replace a transaction (full edit; re-validates and re-freezes the rate) */
        put: operations["updateTransaction"];
        post?: never;
        /** Delete a transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth with assets/liabilities and per-currency exposure */
        get: operations["getNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending by top-level category over a period (base currency) */
        get: operations["getSpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income vs expense per month (base currency) */
        get: operations["getCashFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        ErrorResponse: {
            /** @example bad request */
            error: string;
        };
        AccountListResponse: {
            accounts: components["schemas"]["Account"][];
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["AccountKind"];
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description Minor units, in the account's own currency.
             */
            opening_balance: number;
            balance: components["schemas"]["Money"];
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            interest_rate?: number | null;
            term_months?: number | null;
            /** Format: date */
            maturity_date?: string | null;
            capitalization?: boolean | null;
            /** Format: int64 */
            credit_limit?: number | null;
            /** Format: int64 */
            principal?: number | null;
            /** Format: date */
            start_date?: string | null;
            payment_day?: number | null;
        };
        CreateAccountRequest: {
            name: string;
            kind: components["schemas"]["AccountKind"];
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @default 0
             */
            opening_balance: number;
            interest_rate?: number;
            term_months?: number;
            /** Format: date */
            maturity_date?: string;
            capitalization?: boolean;
            /** Format: int64 */
            credit_limit?: number;
            /** Format: int64 */
            principal?: number;
            /** Format: date */
            start_date?: string;
            payment_day?: number;
        };
        UpdateAccountRequest: {
            name?: string;
            archived?: boolean;
            interest_rate?: number;
            term_months?: number;
            /** Format: date */
            maturity_date?: string;
            capitalization?: boolean;
            /** Format: int64 */
            credit_limit?: number;
            /** Format: int64 */
            principal?: number;
            /** Format: date */
            start_date?: string;
            payment_day?: number;
        };
        CategoryListResponse: {
            categories: components["schemas"]["Category"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
            type: components["schemas"]["CategoryType"];
            icon?: string | null;
            color?: string | null;
            archived: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateCategoryRequest: {
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Format: uuid */
            parent_id?: string;
            icon?: string;
            color?: string;
        };
        UpdateCategoryRequest: {
            name?: string;
            icon?: string;
            color?: string;
            archived?: boolean;
        };
        TransactionListResponse: {
            transactions: components["schemas"]["Transaction"][];
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string | null;
            /** Format: uuid */
            to_account_id?: string | null;
            /** Format: uuid */
            category_id?: string | null;
            amount: components["schemas"]["Money"];
            to_amount?: components["schemas"]["Money"];
            /** @description Frozen FX rate at transaction time; present when currency != base. */
            rate_to_base?: string | null;
            base_amount?: components["schemas"]["Money"];
            note?: string | null;
            tags: string[];
            /** Format: date-time */
            created_at: string;
        };
        CreateTransactionRequest: {
            /**
             * Format: date-time
             * @description Defaults to now when omitted.
             */
            date?: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string;
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /**
             * Format: int64
             * @description Minor units, in the primary account's currency.
             */
            amount: number;
            /**
             * Format: int64
             * @description Required for cross-currency transfers; in the to account's currency.
             */
            to_amount?: number;
            /** @description Required when the primary currency differs from base. Decimal string. */
            rate_to_base?: string;
            note?: string;
            tags?: string[];
        };
        NetWorthReport: {
            base: components["schemas"]["Currency"];
            net_worth: components["schemas"]["Money"];
            assets: components["schemas"]["Money"];
            liabilities: components["schemas"]["Money"];
            by_currency: components["schemas"]["CurrencyExposure"][];
            /** @description Currencies with no known rate, excluded from the base totals. */
            missing_rates: components["schemas"]["Currency"][];
        };
        CurrencyExposure: {
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description Minor units, in this currency.
             */
            assets: number;
            /** Format: int64 */
            liabilities: number;
            /** Format: int64 */
            net: number;
            rate_known: boolean;
            net_in_base?: components["schemas"]["Money"];
        };
        SpendingReport: {
            base: components["schemas"]["Currency"];
            total: components["schemas"]["Money"];
            categories: components["schemas"]["CategorySpend"][];
        };
        CategorySpend: {
            /** Format: uuid */
            category_id: string;
            category_name: string;
            amount: components["schemas"]["Money"];
        };
        CashFlowReport: {
            base: components["schemas"]["Currency"];
            months: components["schemas"]["MonthFlow"][];
        };
        MonthFlow: {
            /** @description YYYY-MM */
            month: string;
            income: components["schemas"]["Money"];
            expense: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
        };
        AmortizationSchedule: {
            currency: components["schemas"]["Currency"];
            monthly_payment: components["schemas"]["Money"];
            total_payment: components["schemas"]["Money"];
            total_interest: components["schemas"]["Money"];
            rows: components["schemas"]["AmortizationRow"][];
        };
        AmortizationRow: {
            period: number;
            /** Format: date */
            date: string;
            payment: components["schemas"]["Money"];
            principal: components["schemas"]["Money"];
            interest: components["schemas"]["Money"];
            balance: components["schemas"]["Money"];
        };
        /** @enum {string} */
        AccountKind: "asset" | "liability";
        /** @enum {string} */
        AccountType: "cash" | "debit_card" | "deposit" | "credit_card" | "loan";
        /**
         * @description ISO 4217 currency code.
         * @example UZS
         */
        Currency: string;
        /** @description Monetary value as integer minor units plus an ISO-4217 currency code. */
        Money: {
            /**
             * Format: int64
             * @description Amount in minor units (e.g. cents). Never floating point.
             * @example 100000
             */
            amount: number;
            currency: components["schemas"]["Currency"];
        };
        /** @enum {string} */
        CategoryType: "expense" | "income";
        /** @enum {string} */
        TransactionType: "expense" | "income" | "transfer";
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AccountId: string;
        CategoryId: string;
        TransactionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Account is in use; archive it instead */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getAmortization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Amortization schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmortizationSchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                type?: components["schemas"]["CategoryType"];
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Category is in use; archive it instead */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                account_id?: string;
                category_id?: string;
                type?: components["schemas"]["TransactionType"];
                date_from?: string;
                date_to?: string;
                tag?: string;
                /** @description Free-text match on the note */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getNetWorth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Net worth report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthReport"];
                };
            };
        };
    };
    getSpending: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spending report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingReport"];
                };
            };
        };
    };
    getCashFlow: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash-flow report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowReport"];
                };
            };
        };
    };
}
