/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { Money } from "./money";
export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client-facing app configuration (base currency, validation thresholds) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts with derived balances */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Get an account with its derived balance */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /** Delete an account; only allowed when it has no transactions */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update mutable account fields */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{id}/amortization": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Amortization schedule for a loan account */
        get: operations["getAmortization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories (expense and income trees) */
        get: operations["listCategories"];
        put?: never;
        /** Create a category or subcategory */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        /** Get a category */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /** Delete a category; only allowed when it has no subcategories or transactions */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Update mutable category fields */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/categories/suggest-icons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Tabler icon names for a category name, using an LLM */
        post: operations["suggestIcons"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search transactions */
        get: operations["listTransactions"];
        put?: never;
        /** Record an expense, income, or transfer */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export expenses and income (matching the given filters) as an .xlsx file */
        get: operations["exportTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Get a transaction */
        get: operations["getTransaction"];
        /** Replace a transaction (full edit; re-validates and re-freezes the rate) */
        put: operations["updateTransaction"];
        post?: never;
        /** Delete a transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Partially update a transaction (currently only its category) */
        patch: operations["patchTransaction"];
        trace?: never;
    };
    "/transactions/{id}/category-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Suggest categories for a transaction (local rules, then an LLM) */
        get: operations["getCategorySuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Get the split breakdown of an expense (your share + per-person owed) */
        get: operations["getTransactionSplit"];
        /** Split an expense across people. Your share stays the expense; each participant's share becomes a transfer into a new receivable account. An empty participant list un-splits the expense. */
        put: operations["setTransactionSplit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category-rule-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List merchants the user never wants to be offered a rule for */
        get: operations["listCategoryRuleBlocks"];
        put?: never;
        /** Never offer a routing rule for this merchant again */
        post: operations["createCategoryRuleBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotently ingest an external transaction (e.g. bank notifications) */
        post: operations["ingestTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a card balance snapshot (e.g. the bot's periodic balance report)
         * @description Upserts the latest reported balance per card (keyed by card_last4). Used for reconciliation against derived account balances. Idempotent.
         */
        post: operations["ingestBalances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare bank-reported card balances against derived account balances */
        get: operations["getReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth with assets/liabilities and per-currency exposure */
        get: operations["getNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending by top-level category over a period (base currency) */
        get: operations["getSpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income vs expense per month (base currency) */
        get: operations["getCashFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projected income/expense/transfer cash flow for a month (base currency) */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List budgets with current-period progress */
        get: operations["listBudgets"];
        put?: never;
        /** Create a budget for an expense category */
        post: operations["createBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a budget */
        delete: operations["deleteBudget"];
        options?: never;
        head?: never;
        /** Update a budget */
        patch: operations["updateBudget"];
        trace?: never;
    };
    "/scheduled-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scheduled (recurring) transactions */
        get: operations["listScheduledTransactions"];
        put?: never;
        /** Create a scheduled (recurring) transaction */
        post: operations["createScheduledTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduled-transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScheduledTransactionId"];
            };
            cookie?: never;
        };
        /** Get a scheduled transaction */
        get: operations["getScheduledTransaction"];
        put?: never;
        post?: never;
        /** Delete a scheduled transaction */
        delete: operations["deleteScheduledTransaction"];
        options?: never;
        head?: never;
        /** Update a scheduled transaction (full template + recurrence) */
        patch: operations["updateScheduledTransaction"];
        trace?: never;
    };
    "/category-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List merchant → category ingest routing rules */
        get: operations["listCategoryRules"];
        put?: never;
        /** Create a merchant → category routing rule */
        post: operations["createCategoryRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryRuleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a routing rule */
        delete: operations["deleteCategoryRule"];
        options?: never;
        head?: never;
        /** Update a routing rule */
        patch: operations["updateCategoryRule"];
        trace?: never;
    };
    "/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** VAPID public key the browser uses to subscribe to push (empty when push is disabled) */
        get: operations["getPushPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a Web Push subscription for the current device */
        post: operations["subscribePush"];
        /** Remove a Web Push subscription by endpoint */
        delete: operations["unsubscribePush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List receipt headers (no items), newest first */
        get: operations["listReceipts"];
        put?: never;
        /** Upload a fiscal QR url + receipt photo; scrape and parse asynchronously */
        post: operations["createReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        /** Get a receipt with its parsed items */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{id}/transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Link the receipt to a transaction (one transaction per receipt) */
        put: operations["linkReceiptTransaction"];
        post?: never;
        /** Remove the receipt's transaction link */
        delete: operations["unlinkReceiptTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{id}/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run the parser over the receipt's stored HTML */
        post: operations["reparseReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        AppConfig: {
            base_currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description A note is required when a transaction amount exceeds this many minor units.
             */
            note_required_above: number;
        };
        ErrorResponse: {
            /** @example bad request */
            error: string;
        };
        PushPublicKeyResponse: {
            /** @description VAPID public key (base64url). Empty when push is disabled server-side. */
            key: string;
        };
        /** @description Mirrors the browser PushSubscription.toJSON() shape. */
        PushSubscriptionRequest: {
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
        };
        AccountListResponse: {
            accounts: components["schemas"]["Account"][];
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["AccountKind"];
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            opening_balance: components["schemas"]["Money"];
            balance: components["schemas"]["Money"];
            archived: boolean;
            /** @description When false, the account is excluded from net-worth totals and currency exposure. */
            include_in_net_worth: boolean;
            /** Format: date-time */
            created_at: string;
            /** @description Card identifier used to route external ingest to this account. */
            card_last4?: string | null;
            interest_rate?: number | null;
            term_months?: number | null;
            /** Format: date */
            maturity_date?: string | null;
            capitalization?: boolean | null;
            credit_limit?: components["schemas"]["Money"];
            principal?: components["schemas"]["Money"];
            /** Format: date */
            start_date?: string | null;
            payment_day?: number | null;
        };
        CreateAccountRequest: {
            name: string;
            kind: components["schemas"]["AccountKind"];
            type: components["schemas"]["AccountType"];
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @default 0
             */
            opening_balance: number;
            /** @default true */
            include_in_net_worth: boolean;
            interest_rate?: number;
            term_months?: number;
            /** Format: date */
            maturity_date?: string;
            capitalization?: boolean;
            /** Format: int64 */
            credit_limit?: number;
            /** Format: int64 */
            principal?: number;
            /** Format: date */
            start_date?: string;
            payment_day?: number;
            card_last4?: string;
        };
        UpdateAccountRequest: {
            name?: string;
            archived?: boolean;
            include_in_net_worth?: boolean;
            interest_rate?: number;
            term_months?: number;
            /** Format: date */
            maturity_date?: string;
            capitalization?: boolean;
            /** Format: int64 */
            credit_limit?: number;
            /** Format: int64 */
            principal?: number;
            /** Format: date */
            start_date?: string;
            payment_day?: number;
            card_last4?: string;
        };
        CategoryListResponse: {
            categories: components["schemas"]["Category"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
            type: components["schemas"]["CategoryType"];
            icon?: string | null;
            color?: string | null;
            archived: boolean;
            /** @description When true, the category is hidden from the categorize picker. */
            hidden_in_picker: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateCategoryRequest: {
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Format: uuid */
            parent_id?: string;
            icon?: string;
            color?: string;
            hidden_in_picker?: boolean;
        };
        UpdateCategoryRequest: {
            name?: string;
            icon?: string;
            color?: string;
            archived?: boolean;
            hidden_in_picker?: boolean;
        };
        CategoryRule: {
            /** Format: uuid */
            id: string;
            /** @description Case-insensitive merchant substring that routes ingest to the category. */
            pattern: string;
            /** Format: uuid */
            category_id: string;
            category_name: string;
            /** Format: date-time */
            created_at: string;
        };
        CategoryRuleListResponse: {
            rules: components["schemas"]["CategoryRule"][];
        };
        CreateCategoryRuleRequest: {
            pattern: string;
            /** Format: uuid */
            category_id: string;
        };
        UpdateCategoryRuleRequest: {
            pattern?: string;
            /** Format: uuid */
            category_id?: string;
        };
        SuggestIconsRequest: {
            name: string;
            type: components["schemas"]["CategoryType"];
        };
        SuggestIconsResponse: {
            /** @description Tabler icon names in kebab-case (e.g. "shopping-cart"), most relevant first. */
            icons: string[];
        };
        TransactionListResponse: {
            transactions: components["schemas"]["Transaction"][];
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string | null;
            /** Format: uuid */
            to_account_id?: string | null;
            /** Format: uuid */
            category_id?: string | null;
            amount: components["schemas"]["Money"];
            to_amount?: components["schemas"]["Money"];
            /** @description Frozen FX rate at transaction time; present when currency != base. */
            rate_to_base?: string | null;
            base_amount?: components["schemas"]["Money"];
            note?: string | null;
            tags: string[];
            /** Format: date-time */
            created_at: string;
            /** @description Stable idempotency key for externally-ingested transactions. */
            external_id?: string | null;
            transfer_group_id?: string | null;
            /** @description Ties a split expense to its per-person receivable transfer legs. */
            split_group_id?: string | null;
            /**
             * Format: uuid
             * @description The scanned fiscal receipt linked to this transaction, if any.
             */
            receipt_id?: string | null;
        };
        SplitParticipantInput: {
            /** @description The person who owes you this share. */
            name: string;
            /**
             * Format: int64
             * @description This person's share, in the paying account's currency (minor units).
             */
            amount: number;
        };
        SetSplitRequest: {
            /**
             * Format: int64
             * @description Your own share; becomes the expense amount. Plus the sum of participants it must equal the original bill.
             */
            my_share: number;
            /** @description One entry per friend. Empty un-splits the expense. */
            participants: components["schemas"]["SplitParticipantInput"][];
        };
        SplitParticipant: {
            /** Format: uuid */
            account_id: string;
            name: string;
            amount: components["schemas"]["Money"];
            owed: components["schemas"]["Money"];
        };
        TransactionSplit: {
            split_group_id?: string | null;
            my_share: components["schemas"]["Money"];
            participants: components["schemas"]["SplitParticipant"][];
        };
        CreateTransactionRequest: {
            /**
             * Format: date-time
             * @description Defaults to now when omitted.
             */
            date?: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string;
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /**
             * Format: int64
             * @description Minor units, in the primary account's currency.
             */
            amount: number;
            /**
             * Format: int64
             * @description Required for cross-currency transfers; in the to account's currency.
             */
            to_amount?: number;
            /** @description Required when the primary currency differs from base. Decimal string. */
            rate_to_base?: string;
            note?: string;
            tags?: string[];
        };
        /**
         * @description External transaction (e.g. bank notification). The app owns routing: it
         *     resolves cards to accounts and the merchant to a category. The caller
         *     sends the card(s) and merchant, not account/category ids.
         */
        IngestTransactionRequest: {
            /** @description Stable idempotency key (e.g. tg:<chat>:<msg> or tg:transfer:<lo>-<hi>). */
            external_id: string;
            transfer_group_id?: string;
            /** Format: date-time */
            date?: string;
            type: components["schemas"]["TransactionType"];
            /** @description Card whose account money leaves (expense, transfer). Resolved app-side. */
            from_card_last4?: string;
            /** @description Card whose account money enters (income, transfer). Resolved app-side. */
            to_card_last4?: string;
            /** @description Raw merchant/source text; used to route to a category and stored as the note. */
            merchant?: string;
            /** Format: int64 */
            amount: number;
            /** Format: int64 */
            to_amount?: number;
            rate_to_base?: string;
            tags?: string[];
        };
        PatchTransactionRequest: {
            /**
             * Format: uuid
             * @description New category; its type must match the transaction's type.
             */
            category_id: string;
        };
        CategorySuggestion: {
            /** Format: uuid */
            category_id: string;
            category_name: string;
            source: components["schemas"]["SuggestionSource"];
        };
        CategorySuggestionsResponse: {
            suggestions: components["schemas"]["CategorySuggestion"][];
        };
        CategoryRuleBlock: {
            merchant: string;
            /** Format: date-time */
            created_at: string;
        };
        CategoryRuleBlockListResponse: {
            blocks: components["schemas"]["CategoryRuleBlock"][];
        };
        CreateCategoryRuleBlockRequest: {
            merchant: string;
        };
        NetWorthReport: {
            base: components["schemas"]["Currency"];
            net_worth: components["schemas"]["Money"];
            assets: components["schemas"]["Money"];
            liabilities: components["schemas"]["Money"];
            by_currency: components["schemas"]["CurrencyExposure"][];
            /** @description Currencies with no known rate, excluded from the base totals. */
            missing_rates: components["schemas"]["Currency"][];
        };
        CurrencyExposure: {
            currency: components["schemas"]["Currency"];
            assets: components["schemas"]["Money"];
            liabilities: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
            rate_known: boolean;
            net_in_base?: components["schemas"]["Money"];
        };
        /**
         * @description A snapshot of reported card balances (e.g. the bot's periodic report).
         *     Each entry is upserted by card_last4; the latest snapshot wins.
         */
        BalanceSnapshotRequest: {
            /** Format: date-time */
            reported_at: string;
            /** @description Origin label (e.g. "humo"). */
            source?: string;
            balances: components["schemas"]["BalanceSnapshotEntry"][];
        };
        BalanceSnapshotEntry: {
            /** @description Card identifier used to route to an account. */
            card_last4: string;
            /** @description Display label for the issuing bank (e.g. "TBCBANK"). */
            bank?: string;
            /**
             * Format: int64
             * @description Reported balance in minor units.
             */
            amount: number;
            currency: components["schemas"]["Currency"];
        };
        ReconciliationReport: {
            base: components["schemas"]["Currency"];
            rows: components["schemas"]["ReconciliationRow"][];
        };
        ReconciliationRow: {
            card_last4: string;
            bank?: string | null;
            /** Format: uuid */
            account_id: string;
            account_name: string;
            reported: components["schemas"]["Money"];
            derived: components["schemas"]["Money"];
            delta?: components["schemas"]["Money"];
            in_sync: boolean;
            /** @description Reported currency differs from the account currency. */
            currency_mismatch: boolean;
            /** Format: date-time */
            reported_at: string;
        };
        SpendingReport: {
            base: components["schemas"]["Currency"];
            total: components["schemas"]["Money"];
            categories: components["schemas"]["CategorySpend"][];
        };
        CategorySpend: {
            /** Format: uuid */
            category_id: string;
            category_name: string;
            amount: components["schemas"]["Money"];
        };
        CashFlowReport: {
            base: components["schemas"]["Currency"];
            months: components["schemas"]["MonthFlow"][];
        };
        MonthFlow: {
            /** @description YYYY-MM */
            month: string;
            income: components["schemas"]["Money"];
            expense: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
        };
        /** @description Projected cash flow for a month from scheduled transactions, budgets and credit-card usage. Expense is total planned outflow (expenses, transfers, budgets and card usage combined); net = income − expense. */
        ForecastReport: {
            base: components["schemas"]["Currency"];
            /** @description YYYY-MM */
            month: string;
            income: components["schemas"]["Money"];
            expense: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
            lines: components["schemas"]["ForecastLine"][];
            /** @description Budget limits normalized to a monthly equivalent; also summed into expense. */
            budget_lines: components["schemas"]["ForecastBudgetLine"][];
            /** @description Per credit-card spend charged this month (paid later); also summed into expense. */
            credit_card_lines: components["schemas"]["ForecastCreditCardLine"][];
            /** @description Currencies with no known rate; their schedules are omitted from totals. */
            missing_rates: string[];
        };
        ForecastLine: {
            /** Format: uuid */
            schedule_id: string;
            name?: string | null;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            category_id?: string | null;
            /** Format: uuid */
            from_account_id?: string | null;
            /** Format: uuid */
            to_account_id?: string | null;
            amount: components["schemas"]["Money"];
            /** @description Number of times this schedule occurs in the month. */
            occurrences: number;
        };
        ForecastBudgetLine: {
            /** Format: uuid */
            budget_id: string;
            /** Format: uuid */
            category_id: string;
            period: components["schemas"]["BudgetPeriod"];
            amount: components["schemas"]["Money"];
        };
        ForecastCreditCardLine: {
            /** Format: uuid */
            account_id: string;
            amount: components["schemas"]["Money"];
        };
        AmortizationSchedule: {
            currency: components["schemas"]["Currency"];
            monthly_payment: components["schemas"]["Money"];
            total_payment: components["schemas"]["Money"];
            total_interest: components["schemas"]["Money"];
            rows: components["schemas"]["AmortizationRow"][];
        };
        AmortizationRow: {
            period: number;
            /** Format: date */
            date: string;
            payment: components["schemas"]["Money"];
            principal: components["schemas"]["Money"];
            interest: components["schemas"]["Money"];
            balance: components["schemas"]["Money"];
        };
        BudgetListResponse: {
            budgets: components["schemas"]["Budget"][];
        };
        Budget: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            category_id: string;
            category_name: string;
            period: components["schemas"]["BudgetPeriod"];
            amount: components["schemas"]["Money"];
            spent: components["schemas"]["Money"];
            remaining: components["schemas"]["Money"];
            /** @description spent / amount × 100 (may exceed 100 when overspent) */
            percent: number;
            rollover: boolean;
            /** Format: date */
            start_period?: string | null;
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
        };
        CreateBudgetRequest: {
            /** Format: uuid */
            category_id: string;
            period?: components["schemas"]["BudgetPeriod"];
            /**
             * Format: int64
             * @description Limit in base-currency minor units.
             */
            amount: number;
            rollover?: boolean;
            /** Format: date */
            start_period?: string;
        };
        UpdateBudgetRequest: {
            period?: components["schemas"]["BudgetPeriod"];
            /** Format: int64 */
            amount?: number;
            rollover?: boolean;
            /** Format: date */
            start_period?: string;
        };
        ScheduledTransactionListResponse: {
            scheduled_transactions: components["schemas"]["ScheduledTransaction"][];
        };
        /** @description A transaction template plus a recurrence rule and scheduling state. */
        ScheduledTransaction: {
            /** Format: uuid */
            id: string;
            /** @description Optional label for the schedule (e.g. "Rent"). */
            name?: string | null;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string | null;
            /** Format: uuid */
            to_account_id?: string | null;
            /** Format: uuid */
            category_id?: string | null;
            amount: components["schemas"]["Money"];
            to_amount?: components["schemas"]["Money"];
            /** @description Frozen FX rate applied to each materialized run; present when currency != base. */
            rate_to_base?: string | null;
            note?: string | null;
            tags: string[];
            frequency: components["schemas"]["ScheduleFrequency"];
            /** @description Recur every N units of the frequency. */
            interval: number;
            /**
             * Format: date
             * @description Recurrence anchor; the first occurrence.
             */
            start_date: string;
            /**
             * Format: date
             * @description Last date an occurrence may fall on; no end when omitted.
             */
            end_date?: string | null;
            /** @description Excluded from the forecast while paused. */
            paused: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateScheduledTransactionRequest: {
            name?: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string;
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /**
             * Format: int64
             * @description Minor units, in the primary account's currency.
             */
            amount: number;
            /**
             * Format: int64
             * @description Required for cross-currency transfers; in the to account's currency.
             */
            to_amount?: number;
            /** @description Required when the primary currency differs from base. Decimal string. */
            rate_to_base?: string;
            note?: string;
            tags?: string[];
            frequency: components["schemas"]["ScheduleFrequency"];
            /** @default 1 */
            interval: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string;
            paused?: boolean;
        };
        /** @description Full replace of the schedule template and recurrence. */
        UpdateScheduledTransactionRequest: {
            name?: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            from_account_id?: string;
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /** Format: int64 */
            amount: number;
            /** Format: int64 */
            to_amount?: number;
            rate_to_base?: string;
            note?: string;
            tags?: string[];
            frequency: components["schemas"]["ScheduleFrequency"];
            /** @default 1 */
            interval: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string;
            paused?: boolean;
        };
        ReceiptCreated: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ReceiptStatus"];
        };
        ReceiptListResponse: {
            receipts: components["schemas"]["Receipt"][];
        };
        Receipt: {
            /** Format: uuid */
            id: string;
            qr_url: string;
            status: components["schemas"]["ReceiptStatus"];
            /** @description Failure reason when status is failed. */
            error?: string | null;
            terminal_id?: string | null;
            receipt_seq?: number | null;
            fiscal_sign?: string | null;
            receipt_type?: string | null;
            merchant_name?: string | null;
            merchant_tin?: string | null;
            merchant_address?: string | null;
            device_name?: string | null;
            serial_number?: string | null;
            card_type?: string | null;
            merchant_lat?: string | null;
            merchant_lng?: string | null;
            paid_cash?: components["schemas"]["Money"];
            paid_card?: components["schemas"]["Money"];
            total_amount?: components["schemas"]["Money"];
            total_vat?: components["schemas"]["Money"];
            /** @description Object key of the receipt photo in storage. */
            photo_key?: string | null;
            /** Format: date-time */
            received_at?: string | null;
            /** Format: date-time */
            scraped_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: uuid
             * @description Linked transaction, if any.
             */
            transaction_id?: string | null;
            items: components["schemas"]["ReceiptItem"][];
        };
        ReceiptLinkRequest: {
            /** Format: uuid */
            transaction_id: string;
        };
        ReceiptItem: {
            name: string;
            quantity: string;
            price: components["schemas"]["Money"];
            vat_amount: components["schemas"]["Money"];
            vat_rate: number;
            discount?: components["schemas"]["Money"];
            other?: components["schemas"]["Money"];
            barcode?: string | null;
            ikpu_code?: string | null;
            ikpu_name?: string | null;
            unit?: string | null;
            marking_code?: string | null;
            consignor_tin?: string | null;
        };
        /**
         * @description ISO 4217 currency code.
         * @example UZS
         */
        Currency: string;
        /** @enum {string} */
        AccountKind: "asset" | "liability";
        /** @enum {string} */
        AccountType: "cash" | "debit_card" | "deposit" | "credit_card" | "loan" | "receivable";
        /** @description Monetary value as integer minor units plus an ISO-4217 currency code. */
        Money: Money;
        /** @enum {string} */
        CategoryType: "expense" | "income";
        /** @enum {string} */
        TransactionType: "expense" | "income" | "transfer";
        /**
         * @description Where a category suggestion came from.
         * @enum {string}
         */
        SuggestionSource: "rule" | "ai";
        /** @enum {string} */
        BudgetPeriod: "weekly" | "monthly" | "yearly";
        /**
         * @description How often a scheduled transaction recurs (combined with an interval). "once" is a one-time item on its start date.
         * @enum {string}
         */
        ScheduleFrequency: "once" | "daily" | "weekly" | "monthly" | "yearly";
        /**
         * @description Lifecycle of an async receipt scrape+parse.
         * @enum {string}
         */
        ReceiptStatus: "pending" | "html_received" | "success" | "failed";
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        BudgetId: string;
        CategoryRuleId: string;
        ScheduledTransactionId: string;
        AccountId: string;
        CategoryId: string;
        TransactionId: string;
        ReceiptId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description App configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Account is in use; archive it instead */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getAmortization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Amortization schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmortizationSchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                type?: components["schemas"]["CategoryType"];
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Category is in use; archive it instead */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    suggestIcons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestIconsRequest"];
            };
        };
        responses: {
            /** @description Suggested icon names, most relevant first. Empty when suggestions are not configured or the upstream model is unavailable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestIconsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                account_id?: string;
                category_id?: string;
                type?: components["schemas"]["TransactionType"];
                date_from?: string;
                date_to?: string;
                tag?: string;
                /** @description When true, return only transactions in the Uncategorized buckets. */
                uncategorized?: boolean;
                /** @description Free-text match on the note */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    exportTransactions: {
        parameters: {
            query?: {
                account_id?: string;
                category_id?: string;
                /** @description Restrict to a single type; transfers are always excluded. */
                type?: components["schemas"]["TransactionType"];
                date_from?: string;
                date_to?: string;
                tag?: string;
                /** @description Free-text match on the note */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spreadsheet with datetime, amount, category name and note columns */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategorySuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked category suggestions, most relevant first. Empty when nothing matches and suggestions are unavailable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySuggestionsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTransactionSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Split breakdown (empty participants when not split) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionSplit"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setTransactionSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSplitRequest"];
            };
        };
        responses: {
            /** @description Updated split breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionSplit"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategoryRuleBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocked merchants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleBlockListResponse"];
                };
            };
        };
    };
    createCategoryRuleBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRuleBlockRequest"];
            };
        };
        responses: {
            /** @description Merchant blocked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleBlock"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    ingestTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestTransactionRequest"];
            };
        };
        responses: {
            /** @description Already ingested (deduped by external_id) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalanceSnapshotRequest"];
            };
        };
        responses: {
            /** @description Snapshot accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationReport"];
                };
            };
        };
    };
    getNetWorth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Net worth report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthReport"];
                };
            };
        };
    };
    getSpending: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spending report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingReport"];
                };
            };
        };
    };
    getCashFlow: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash-flow report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowReport"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query?: {
                /** @description Target month as YYYY-MM. Defaults to the current month. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastReport"];
                };
            };
        };
    };
    listBudgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budgets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetListResponse"];
                };
            };
        };
    };
    createBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listScheduledTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduled transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTransactionListResponse"];
                };
            };
        };
    };
    createScheduledTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduledTransactionRequest"];
            };
        };
        responses: {
            /** @description Schedule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTransaction"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getScheduledTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScheduledTransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTransaction"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteScheduledTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScheduledTransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateScheduledTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ScheduledTransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduledTransactionRequest"];
            };
        };
        responses: {
            /** @description Schedule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTransaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategoryRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleListResponse"];
                };
            };
        };
    };
    createCategoryRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRuleRequest"];
            };
        };
        responses: {
            /** @description Rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRule"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteCategoryRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryRuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCategoryRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryRuleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRuleRequest"];
            };
        };
        responses: {
            /** @description Rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPushPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushPublicKeyResponse"];
                };
            };
        };
    };
    subscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    unsubscribePush: {
        parameters: {
            query: {
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listReceipts: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipts list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptListResponse"];
                };
            };
        };
    };
    createReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Full ofd.soliq.uz check URL from the receipt QR code. */
                    qr_url: string;
                    /**
                     * Format: binary
                     * @description JPEG image of the paper receipt.
                     */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description Receipt accepted; processing in the background */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    linkReceiptTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptLinkRequest"];
            };
        };
        responses: {
            /** @description Updated receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description That transaction is already linked to another receipt */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlinkReceiptTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reparseReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReceiptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Re-parsed receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
