import type { components } from './schema'

type S = components['schemas']

export type Money = S['Money']
export type AppConfig = S['AppConfig']
export type Account = S['Account']
export type Category = S['Category']
export type Transaction = S['Transaction']
export type NetWorthReport = S['NetWorthReport']
export type AmortizationSchedule = S['AmortizationSchedule']
export type AmortizationRow = S['AmortizationRow']
export type SpendingReport = S['SpendingReport']
export type CashFlowReport = S['CashFlowReport']
export type ForecastReport = S['ForecastReport']
export type ForecastLine = S['ForecastLine']
export type ForecastBudgetLine = S['ForecastBudgetLine']
export type ForecastCreditCardLine = S['ForecastCreditCardLine']
export type ReconciliationReport = S['ReconciliationReport']
export type ReconciliationRow = S['ReconciliationRow']
export type CategorySuggestion = S['CategorySuggestion']
export type CategoryRuleBlock = S['CategoryRuleBlock']

export type CreateAccountRequest = S['CreateAccountRequest']
export type UpdateAccountRequest = S['UpdateAccountRequest']
export type CreateCategoryRequest = S['CreateCategoryRequest']
export type UpdateCategoryRequest = S['UpdateCategoryRequest']
export type CategoryRule = S['CategoryRule']
export type CreateCategoryRuleRequest = S['CreateCategoryRuleRequest']
export type UpdateCategoryRuleRequest = S['UpdateCategoryRuleRequest']
export type CreateTransactionRequest = S['CreateTransactionRequest']
export type TransactionSplit = S['TransactionSplit']
export type SplitParticipant = S['SplitParticipant']
export type SetSplitRequest = S['SetSplitRequest']
export type PushSubscriptionRequest = S['PushSubscriptionRequest']
export type Budget = S['Budget']
export type CreateBudgetRequest = S['CreateBudgetRequest']
export type UpdateBudgetRequest = S['UpdateBudgetRequest']
export type BudgetPeriod = S['BudgetPeriod']

export type ScheduledTransaction = S['ScheduledTransaction']
export type CreateScheduledTransactionRequest = S['CreateScheduledTransactionRequest']
export type UpdateScheduledTransactionRequest = S['UpdateScheduledTransactionRequest']
export type ScheduleFrequency = S['ScheduleFrequency']

export type Receipt = S['Receipt']
export type ReceiptItem = S['ReceiptItem']
export type ReceiptCreated = S['ReceiptCreated']
export type ReceiptStatus = S['ReceiptStatus']

export type AccountKind = S['AccountKind']
export type AccountType = S['AccountType']
export type CategoryType = S['CategoryType']
export type TransactionType = S['TransactionType']
