export interface IconDef {
  name: string
  keywords?: string
}

export interface IconGroup {
  label: string
  icons: IconDef[]
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: 'Money',
    icons: [
      { name: 'wallet' },
      { name: 'cash', keywords: 'money bill' },
      { name: 'coin', keywords: 'money' },
      { name: 'coins', keywords: 'money savings' },
      { name: 'credit-card', keywords: 'card payment' },
      { name: 'pig-money', keywords: 'savings piggy bank' },
      { name: 'moneybag', keywords: 'money bag salary' },
      { name: 'currency-dollar', keywords: 'usd money' },
      { name: 'businessplan', keywords: 'investment plan' },
      { name: 'receipt', keywords: 'bill invoice' },
      { name: 'receipt-tax', keywords: 'tax' },
      { name: 'report-money', keywords: 'income report' },
      { name: 'percentage', keywords: 'interest rate' },
      { name: 'discount-2', keywords: 'sale discount' },
      { name: 'gift-card', keywords: 'voucher' },
      { name: 'chart-line', keywords: 'investment stocks' },
      { name: 'trending-up', keywords: 'income gain profit' },
      { name: 'trending-down', keywords: 'loss expense' },
      { name: 'briefcase', keywords: 'work salary job' },
    ],
  },
  {
    label: 'Food & Drink',
    icons: [
      { name: 'shopping-cart', keywords: 'groceries' },
      { name: 'shopping-bag', keywords: 'groceries shop' },
      { name: 'basket', keywords: 'groceries' },
      { name: 'meat', keywords: 'food' },
      { name: 'fish', keywords: 'food seafood' },
      { name: 'egg', keywords: 'food' },
      { name: 'apple', keywords: 'fruit food' },
      { name: 'carrot', keywords: 'vegetable food' },
      { name: 'bread', keywords: 'bakery food' },
      { name: 'cheese', keywords: 'food dairy' },
      { name: 'milk', keywords: 'dairy drink' },
      { name: 'pizza', keywords: 'food fast' },
      { name: 'salad', keywords: 'food healthy' },
      { name: 'soup', keywords: 'food' },
      { name: 'ice-cream', keywords: 'dessert food' },
      { name: 'coffee', keywords: 'drink cafe' },
      { name: 'cup', keywords: 'drink tea' },
      { name: 'beer', keywords: 'drink alcohol' },
      { name: 'bottle', keywords: 'drink water' },
      { name: 'tools-kitchen-2', keywords: 'restaurant dining food' },
    ],
  },
  {
    label: 'Home & Bills',
    icons: [
      { name: 'home', keywords: 'house rent' },
      { name: 'home-2', keywords: 'house rent mortgage' },
      { name: 'building', keywords: 'apartment rent' },
      { name: 'building-store', keywords: 'shop store' },
      { name: 'bed', keywords: 'hotel furniture' },
      { name: 'sofa', keywords: 'furniture' },
      { name: 'lamp', keywords: 'furniture light' },
      { name: 'wash-machine', keywords: 'laundry appliance' },
      { name: 'plug', keywords: 'electricity utility' },
      { name: 'bulb', keywords: 'electricity light' },
      { name: 'bolt', keywords: 'electricity power utility' },
      { name: 'droplet', keywords: 'water utility' },
      { name: 'flame', keywords: 'gas heating utility' },
      { name: 'trash', keywords: 'garbage waste' },
      { name: 'recycle', keywords: 'waste' },
      { name: 'phone', keywords: 'bill telephone' },
      { name: 'wifi', keywords: 'internet bill' },
      { name: 'world-www', keywords: 'internet bill domain' },
      { name: 'cloud', keywords: 'storage subscription' },
      { name: 'server', keywords: 'hosting subscription' },
    ],
  },
  {
    label: 'Transport',
    icons: [
      { name: 'car', keywords: 'auto vehicle' },
      { name: 'car-suv', keywords: 'auto vehicle' },
      { name: 'gas-station', keywords: 'fuel petrol car' },
      { name: 'parking', keywords: 'car' },
      { name: 'bus', keywords: 'transit public' },
      { name: 'train', keywords: 'transit rail' },
      { name: 'plane', keywords: 'flight travel' },
      { name: 'plane-departure', keywords: 'flight travel airport' },
      { name: 'bike', keywords: 'cycle' },
      { name: 'scooter', keywords: 'moped' },
      { name: 'walk', keywords: 'foot' },
      { name: 'road', keywords: 'toll travel' },
      { name: 'ticket', keywords: 'transit travel' },
      { name: 'luggage', keywords: 'travel trip' },
      { name: 'sailboat', keywords: 'boat travel' },
      { name: 'map-pin', keywords: 'location travel' },
    ],
  },
  {
    label: 'Health',
    icons: [
      { name: 'heartbeat', keywords: 'health medical' },
      { name: 'heart-rate-monitor', keywords: 'health medical' },
      { name: 'stethoscope', keywords: 'doctor medical' },
      { name: 'pill', keywords: 'medicine pharmacy' },
      { name: 'vaccine', keywords: 'medical injection' },
      { name: 'dental', keywords: 'dentist teeth' },
      { name: 'first-aid-kit', keywords: 'medical emergency' },
      { name: 'building-hospital', keywords: 'medical clinic' },
      { name: 'barbell', keywords: 'gym fitness sport' },
      { name: 'run', keywords: 'fitness sport exercise' },
      { name: 'yoga', keywords: 'fitness wellness' },
      { name: 'swimming', keywords: 'sport pool' },
      { name: 'massage', keywords: 'spa wellness' },
      { name: 'mood-smile', keywords: 'wellbeing fun' },
    ],
  },
  {
    label: 'Lifestyle',
    icons: [
      { name: 'shirt', keywords: 'clothes clothing fashion' },
      { name: 'shoe', keywords: 'clothes footwear' },
      { name: 'hanger', keywords: 'clothes wardrobe' },
      { name: 'needle-thread', keywords: 'tailor sewing' },
      { name: 'scissors', keywords: 'haircut barber salon' },
      { name: 'spray', keywords: 'cosmetics beauty' },
      { name: 'gift', keywords: 'present' },
      { name: 'movie', keywords: 'cinema entertainment' },
      { name: 'music', keywords: 'entertainment' },
      { name: 'speakerphone', keywords: 'audio sound' },
      { name: 'volume', keywords: 'audio sound' },
      { name: 'headphones', keywords: 'audio music' },
      { name: 'camera', keywords: 'photo hobby' },
      { name: 'device-gamepad-2', keywords: 'games entertainment' },
      { name: 'ball-football', keywords: 'sport soccer' },
      { name: 'device-laptop', keywords: 'electronics tech computer' },
      { name: 'device-mobile', keywords: 'phone electronics' },
      { name: 'device-tv', keywords: 'electronics' },
    ],
  },
  {
    label: 'Other',
    icons: [
      { name: 'school', keywords: 'education tuition' },
      { name: 'book', keywords: 'education reading' },
      { name: 'books', keywords: 'education library' },
      { name: 'backpack', keywords: 'school kids' },
      { name: 'pencil', keywords: 'stationery school' },
      { name: 'baby-carriage', keywords: 'kids children family' },
      { name: 'dog', keywords: 'pet animal' },
      { name: 'cat', keywords: 'pet animal' },
      { name: 'paw', keywords: 'pet animal vet' },
      { name: 'building-church', keywords: 'donation charity' },
      { name: 'calendar-event', keywords: 'subscription recurring' },
      { name: 'repeat', keywords: 'subscription recurring' },
      { name: 'user', keywords: 'personal' },
      { name: 'users', keywords: 'family people' },
      { name: 'heart', keywords: 'donation love' },
      { name: 'star', keywords: 'favorite' },
      { name: 'award', keywords: 'reward bonus' },
      { name: 'trophy', keywords: 'reward win' },
      { name: 'tree', keywords: 'nature garden' },
      { name: 'leaf', keywords: 'nature garden eco' },
      { name: 'flower', keywords: 'garden plants' },
      { name: 'umbrella', keywords: 'insurance' },
    ],
  },
]

// Flat name list, handy for validation/lookups.
export const ICON_NAMES: string[] = ICON_GROUPS.flatMap((g) => g.icons.map((i) => i.name))
